import { build } from "esbuild";
import { fileURLToPath } from "node:url";
import path from "node:path";

const root = path.resolve(path.dirname(fileURLToPath(import.meta.url)), "..");
const outDir = path.join(root, "custom_components", "naolib", "www");

// Each entry point must bundle into a single file: the card is imported over the
// network by the loader, and extra requests reintroduce the flaky-import failures
// documented in the 2.5.0 beta cycle.
const entries = [
    { in: "src/loader.js", out: "naolib-loader.js" },
    { in: "src/index.js", out: "naolib-card.js" },
];

const banner = [
    "/* Generated by scripts/build.mjs -- do not edit.",
    " * Sources live in src/; run `npm run build` after any change.",
    " */",
].join("\n");

await Promise.all(
    entries.map((entry) =>
        build({
            entryPoints: [path.join(root, entry.in)],
            outfile: path.join(outDir, entry.out),
            bundle: true,
            format: "esm",
            target: ["es2020"],
            charset: "utf8",
            legalComments: "none",
            banner: { js: banner },
        }),
    ),
);

console.log(`Built ${entries.length} bundles into ${path.relative(root, outDir)}`);
